---
- name: Upgrade all packages to the latest version
  package:
    name: '*'
    state: latest
    update_cache: yes

- name: BLOCK DOCKER INSTALL.
  block:
    - name: REMOVE DOCKER WITH DEPENDENCES.
      package:
        name: "{{ item }}"
        state: absent
      with_items:  
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine

    - name: INSTALL DOCKER PKG.
      package:
        name: "{{ item }}"
        state: latest
      with_items: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
      register: docker_install_status
      
    - name: install the package, force upgrade
      pip:
        name: pip
        executable: pip
        state: latest

    - name: INSTALLING PYTHON PKG FOR DOCKER MANAGMENT.
      pip:
        name: ['requests', 'urllib3','docker-compose']
        state: latest
        extra_args: "--ignore-installed"

    - name: restarted docker
      service:
        name: docker
        state: restarted
        enabled: yes
      when: docker_install_status.changed == true

  become: true

- name: BLOCK ADD USERS TO GROUP DOCKER. 
  block:
    - name: CREATE DOCKER GROUP.
      group:
        name: docker
        state: present

    - name: ADD USERS IN TO DOCKER GROUP.
      user:
        name: "{{ item }}"
        groups: docker
      with_items: "{{ docker_users }}"

  become: true

- name: BLOCK FOR CLEANING CACHE.
  block:
    - name: YUM CLEAN METADATA.
      command: 
        cmd: yum clean all 

    - name: DELETE CACHE FOLDER.
      file:
        path: "{{ cache_path[ansible_facts['distribution_file_variety'] | lower] }}"
        state: absent
